usStateNames = {
    'AK': 'alaska',
    'AL': 'alabama',
    'AR': 'arkansas',
    'AS': 'american samoa',
    'AZ': 'arizona',
    'CA': 'california',
    'CO': 'colorado',
    'CT': 'connecticut',
    'DC': 'district of columbia',
    'DE': 'delaware',
    'FL': 'florida',
    'GA': 'georgia',
    'GU': 'guam',
    'HI': 'hawaii',
    'IA': 'iowa',
    'ID': 'idaho',
    'IL': 'illinois',
    'IN': 'indiana',
    'KS': 'kansas',
    'KY': 'kentucky',
    'LA': 'louisiana',
    'MA': 'massachusetts',
    'MD': 'maryland',
    'ME': 'maine',
    'MI': 'michigan',
    'MN': 'minnesota',
    'MO': 'missouri',
    'MP': 'northern mariana islands',
    'MS': 'mississippi',
    'MT': 'montana',
    'NC': 'north carolina',
    'ND': 'north dakota',
    'NE': 'nebraska',
    'NH': 'new hampshire',
    'NJ': 'new jersey',
    'NM': 'new mexico',
    'NV': 'nevada',
    'NY': 'new york',
    'OH': 'ohio',
    'OK': 'oklahoma',
    'OR': 'oregon',
    'PA': 'pennsylvania',
    'PR': 'puerto rico',
    'RI': 'rhode island',
    'SC': 'south carolina',
    'SD': 'south dakota',
    'TN': 'tennessee',
    'TT': 'trust territories',
    'TX': 'texas',
    'UT': 'utah',
    'VA': 'virginia',
    'VI': 'virgin islands',
    'VT': 'vermont',
    'WA': 'washington',
    'WI': 'wisconsin',
    'WV': 'west virginia',
    'WY': 'wyoming'
}

usStateAbbrs = {
    'alabama': 'AL',
    'kentucky': 'KY',
    'ohio': 'OH',
    'alaska': 'AK',
    'louisiana': 'LA',
    'oklahoma': 'OK',
    'arizona': 'AZ',
    'maine': 'ME',
    'oregon': 'OR',
    'arkansas': 'AR',
    'maryland': 'MD',
    'pennsylvania': 'PA',
    'american samoa': 'AS',
    'massachusetts': 'MA',
    'puerto rico': 'PR',
    'california': 'CA',
    'michigan': 'MI',
    'rhode island': 'RI',
    'colorado': 'CO',
    'minnesota': 'MN',
    'south carolina': 'SC',
    'connecticut': 'CT',
    'mississippi': 'MS',
    'south dakota': 'SD',
    'delaware': 'DE',
    'missouri': 'MO',
    'tennessee': 'TN',
    'district of columbia': 'DC',
    'montana': 'MT',
    'texas': 'TX',
    'florida': 'FL',
    'nebraska': 'NE',
    'trust territories': 'TT',
    'georgia': 'GA',
    'nevada': 'NV',
    'utah': 'UT',
    'guam': 'GU',
    'new hampshire': 'NH',
    'vermont': 'VT',
    'hawaii': 'HI',
    'new jersey': 'NJ',
    'virginia': 'VA',
    'idaho': 'ID',
    'new mexico': 'NM',
    'virgin islands': 'VI',
    'illinois': 'IL',
    'new york': 'NY',
    'washington': 'WA',
    'indiana': 'IN',
    'north carolina': 'NC',
    'west virginia': 'WV',
    'iowa': 'IA',
    'north dakota': 'ND',
    'wisconsin': 'WI',
    'kansas': 'KS',
    'northern mariana islands': 'MP',
    'wyoming': 'WY'
}

